
"automatically reload vimrc
autocmd! bufwritepost ~/.vim/vimrc source %

" Enable mouse usage (all modes)
set mouse=a

"Pugins to add:
"snipmate
"nnoremap
"fuzzyfinder
"ctags


"fix tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab

"show numbers and turn off line wrapping
set number
set nowrap

"Set Undo levels
set history=1000
set undolevels=1000

"Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

" Enable syntax highlighting
" You need to reload this file for the change to apply
set background=dark
set showmatch
filetype off
filetype plugin indent on
syntax on

" Color scheme
" mkdir -p ~/.vim/colors && cd ~/.vim/colors
" wget -O wombat256mod.vim http://www.vim.org/scripts/download_script.php?src_id=13400
" comment out Normal and LineNr
set t_Co=256
color wombat256mod

" Setup Pathogen to manage your plugins
" mkdir -p /etc/vim/autoload /etc/vim/bundle
" curl -so /etc/vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim
" Now you can install any plugin into a .vim/bundle/plugin-name/ folder
call pathogen#infect()

" ============================================================================
" Python IDE Setup
" ============================================================================


" Settings for vim-powerline
" cd /etc/vim/bundle
" git clone git://github.com/Lokaltog/vim-powerline.git

set laststatus=2


" Settings for ctrlp
" cd /etc/vim/bundle
" git clone https://github.com/kien/ctrlp.vim.git

let g:ctrlp_max_height = 30
set wildignore+=*.pyc
set wildignore+=*_build/*
set wildignore+=*/coverage/*


" Settings for python-mode
" cd /etc/vim/bundle
" git clone https://github.com/klen/python-mode

map <Leader>g :call RopeGotoDefinition()<CR>
let ropevim_enable_shortcuts = 1
let g:pymode_rope_goto_def_newwin = "vnew"
let g:pymode_rope_extended_complete = 1
let g:pymode_breakpoint = 0
let g:pymode_syntax = 1
let g:pymode_syntax_builtin_objs = 0
let g:pymode_syntax_builtin_funcs = 0
map <Leader>b Oimport ipdb; ipdb.set_trace() # BREAKPOINT<C-c>


" Set available code-checkers: pylint, pyflakes, pep8, mccabe
let g:pymode_lint_checker = "pyflakes,mccabe"

" Load run code plugin
 let g:pymode_run = 1

" Key for run python code
 let g:pymode_run_key = '<F5>'


" Better navigating through omnicomplete option list
" See
" http://stackoverflow.com/questions/2170023/how-to-map-keys-for-popup-menu-in-vim

set completeopt=longest,menuone
function! OmniPopup(action)
    if pumvisible()
        if a:action == 'j'
            return "\<C-N>"
        elseif a:action == 'k'
            return "\<C-P>"
        endif
    endif
    return a:action
endfunction

inoremap <silent><C-j> <C-R>=OmniPopup('j')<CR>
inoremap <silent><C-k> <C-R>=OmniPopup('k')<CR>


" Python folding
" mkdir -p /etc/vim/ftplugin
" wget -O /etc/vim/ftplugin/python_editing.vi http://www.vim.org/scripts/download_script.php?src_id=5492

set nofoldenable

